# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a7885e58eb3c07c15ecf32309c41c5efd515a9428840151ea6af748970fac2fa30c05bf7be8a18a445d7fa2a3125e4cbdc85593c89e6b296a445c08735263aa

test:
  secret_key_base: 4b43978cb414c12fadf4436785823f78a04ac122e6d53de379a72ce212a6d63a3d51c0c6967719fcf37d545b99c9dbafd776ee25ec0f70afde38741056090f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
